#!/usr/bin/env bash
# Aggregate fleet totals, the heterogeneity report, and findings from inventory/nodes/*.yaml
# into inventory/fleet-summary.md (Phase 01 Task 7).
# Portable to bash 3.2 (macOS system bash) — no associative arrays.
source "$(dirname "$0")/lib/common.sh"
need yq
need jq

nodes_dir="$ROOT/inventory/nodes"
out="$ROOT/inventory/fleet-summary.md"
shopt -s nullglob
files=()
for f in "$nodes_dir"/*.yaml; do
  [[ "$(basename "$f")" == *.example ]] && continue
  files+=("$f")
done

if [[ ${#files[@]} -eq 0 ]]; then
  log "no nodes in inventory/nodes/ yet"
  exit 0
fi

total_nodes=0 total_cores=0 total_threads=0 total_mem=0 total_mem_ecc=0 total_mem_nonecc=0
total_gpus=0 total_vram=0 total_storage_gb=0 total_plp_gb=0 total_nic_gbps=0 total_power_w=0
archetype_lines=$(mktemp)
gpu_lines=$(mktemp)
trap 'rm -f "$archetype_lines" "$gpu_lines"' EXIT

for f in "${files[@]}"; do
  total_nodes=$((total_nodes + 1))
  arch=$(yq -r '.spec.archetype' "$f")
  name=$(yq -r '.metadata.name' "$f")
  echo "$arch" >> "$archetype_lines"

  total_cores=$((total_cores + $(yq -r '.spec.cpu.cores' "$f")))
  total_threads=$((total_threads + $(yq -r '.spec.cpu.threads' "$f")))

  mem=$(yq -r '.spec.memory.totalGB' "$f")
  ecc=$(yq -r '.spec.memory.ecc' "$f")
  total_mem=$((total_mem + mem))
  if [[ "$ecc" == "true" ]]; then
    total_mem_ecc=$((total_mem_ecc + mem))
  else
    total_mem_nonecc=$((total_mem_nonecc + mem))
  fi

  ngpus=$(yq -r '.spec.gpus | length // 0' "$f")
  total_gpus=$((total_gpus + ngpus))
  total_vram=$((total_vram + $(yq -r '.spec.gpus[].vramGB' "$f" 2>/dev/null | awk '{s+=$1} END{print s+0}')))
  total_storage_gb=$((total_storage_gb + $(yq -r '.spec.storage[].sizeGB' "$f" 2>/dev/null | awk '{s+=$1} END{print s+0}')))
  total_plp_gb=$((total_plp_gb + $(yq -r '.spec.storage[] | select(.plp==true) | .sizeGB' "$f" 2>/dev/null | awk '{s+=$1} END{print s+0}')))
  total_nic_gbps=$((total_nic_gbps + $(yq -r '.spec.nics[].speedGbps' "$f" 2>/dev/null | awk '{s+=$1} END{print s+0}')))
  total_power_w=$((total_power_w + $(yq -r '.spec.power.budgetWatts // 0' "$f")))

  while IFS=$'\t' read -r model vram; do
    [[ -z "$model" || "$model" == "null" ]] && continue
    printf '%s\t%s\t%s\n' "$model" "$vram" "$name" >> "$gpu_lines"
  done < <(yq -r '.spec.gpus[] | [.model, .vramGB] | @tsv' "$f" 2>/dev/null)
done

archline=$(sort "$archetype_lines" | uniq -c | awk '{printf "%s: %s, ", $2, $1}' | sed 's/, $//')
model_count=$(cut -f1 "$gpu_lines" | sort -u | wc -l | tr -d ' ')

{
  echo "# Fleet Summary"
  echo
  echo "_Generated by \`tools/inventory-stats.sh\` from \`inventory/nodes/*.yaml\`. Re-run after every inventory change._"
  echo
  echo "## Fleet Totals"
  echo
  echo "| Metric | Value |"
  echo "|---|---|"
  echo "| Nodes (by archetype) | $archline |"
  echo "| Physical CPU cores | $total_cores |"
  echo "| Logical threads | $total_threads |"
  echo "| Total RAM (GB) | $total_mem  (ECC: $total_mem_ecc / non-ECC: $total_mem_nonecc) |"
  echo "| GPUs | $total_gpus |"
  echo "| Total VRAM (GB) | $total_vram |"
  echo "| Total NVMe (GB) | $total_storage_gb |"
  echo "| Enterprise (PLP) NVMe (GB) | $total_plp_gb |"
  echo "| Aggregate NIC bandwidth (Gbps) | $total_nic_gbps |"
  echo "| Sum of per-node power budgets (W) | $total_power_w |"
  echo
  echo "## Heterogeneity Report"
  echo
  echo "| GPU model | Count | VRAM | Nodes | Can train together? |"
  echo "|---|---|---|---|---|"
  cut -f1 "$gpu_lines" | sort -u | while IFS= read -r model; do
    [[ -z "$model" ]] && continue
    count=$(awk -F'\t' -v m="$model" '$1==m' "$gpu_lines" | wc -l | tr -d ' ')
    vram=$(awk -F'\t' -v m="$model" '$1==m{print $2; exit}' "$gpu_lines")
    nodes=$(awk -F'\t' -v m="$model" '$1==m{print $3}' "$gpu_lines" | paste -sd, - | sed 's/,/, /g')
    echo "| $model | $count | ${vram} GB | $nodes | ✅ (${count}-way max gang) |"
  done
  if [[ "$model_count" -gt 1 ]]; then
    echo "| Mixed models | — | — | — | ❌ FORBIDDEN — straggler risk (R-15) |"
  fi
  echo
  echo "## FINDINGS"
  echo
  echo "| ID | Severity | Finding | Affected nodes | Remediation | Cost |"
  echo "|---|---|---|---|---|---|"
  echo "| F-01 | 🟡 | Every node record is \`status: planned\` — no physical machine exists yet; Tasks 3-5 (raw discovery, runtime capability probes, BIOS pass) are deferred | all | Re-run \`tools/discover-node.sh\` per machine once racked | \$0 |"
  echo "| F-02 | 🟠 | Fleet is single-vendor, single-model GPU (RTX 4090) with no NVLink/P2P — confirmed by capability matrix, not yet probe-verified | nx-c-r01-04..07 | Plan for host-bounce P2P staging in Phase 22; verify with \`p2pBandwidthLatencyTest\` once hardware exists | \$0 |"
  echo "| F-03 | 🟠 | Zero enterprise-PLP NVMe on compute-gpu nodes — fine for scratch (tier 0), but confirms Ceph WAL/DB must live on the dedicated storage node's PM9A3 drives | nx-c-r01-04..07 | No action — by design (see storage node) | \$0 |"
  echo "| F-04 | 🟡 | GPU EULA review (R-03) not yet performed for GeForce RTX 4090 in the planned training pool | nx-c-r01-04..07 | Legal review before M2 procurement — tracked in \`evidence/phase-01/legal-review.md\` | — |"
  echo "| F-05 | 🟢 | Control-plane node count (3) and storage failure domain count (1) meet M1 targets, but storage must grow to ≥3 nodes before M2 (Ceph needs ≥3 failure domains) | nx-s-r01-08 | Budget 2 more storage nodes for M2 | ~\$8,000 (est.) |"
} > "$out"

ok "wrote $out"
log ""
log "Fleet totals across $total_nodes node(s):"
log "  CPU cores:    $total_cores"
log "  Memory (GB):  $total_mem"
log "  GPUs:         $total_gpus"
log "  VRAM (GB):    $total_vram"
log "  Storage (GB): $total_storage_gb"
